
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: infra/Dockerfile.backend
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app/backend
    command: ["uvicorn", "backend.gateway.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: infra/Dockerfile.backend
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./backend:/app/backend
    command: ["celery", "-A", "backend.workers.worker", "worker", "--loglevel=info"]

  frontend:
    build:
      context: .
      dockerfile: infra/Dockerfile.frontend
    env_file:
      - .env
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  db-data:
